config/routes.rb
Rails.application.routes.draw do
  root "leads#index"

  devise_for :members, path: '', controllers: {
    confirmations: 'members/confirmations',
    passwords: 'members/passwords',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    unlocks: 'members/unlocks'
  }

  devise_for :admins, path: 'admin', controllers: {
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks'
  }

  namespace :admins do
    get "/", to: "admins#index"
    resources :partners
    resources :leads
  end
  
  resources :leads do
    collection do
      post :search
    end
    member do
      post :convert_client
    end
  end

  resources :clients do
    collection do
      post :search
      get :sync_jurnal
    end
    member do
      post :render_sync_modal
      post :unsync_jurnal
    end
  end

  resources :teams do
    collection do
      post :search
    end
    member do
      patch :reactive
    end
  end
  
  resources :activities do
    member do
      post :render_update_modal
    end
  end

  get 'health', to: 'health#show'
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_member!
  before_action :init_repo_queries, :current_user

  def index
    @last_page = 10
    @current_data = 1 #@query_results.count
    @total_data = 25
    @filter_value = 4 #todo temporary, value for need to link filter option
  end

  def create
    render :partial => 'lists', locals: {choice: "anything else", sort: "desc"}
  end

  def show
    @lists = @query_results.take(4)
    @total_pages = 4
    @client = Lead.new(1, SecureRandom.base64(8), ["email a", "email b"], "081222", "Archived", "Sakura")
    @clients_company = @lists
  end

  def search
    if params[:search_sort] == "desc"
      @query_results = @query_results.sort_by{|x| x.company_name.downcase}.reverse!
    else
      @query_results = @query_results.sort_by{|x| x.company_name.downcase}
    end
    
    render :partial => 'lists', locals: {choice: params[:choice], sort: params[:search_sort]}
  end

  def update
    params[:id] # lead = Client.find(params[:id])
    params[:status_id] # update if param exists
    redirect_to client_path(params[:id])
  end

  def destroy
    redirect_to clients_path
  end

  def render_sync_modal
    @client = Lead.new(params[:id], SecureRandom.base64(8), ["email a", "email b"], "081222", "new lead", "Budi")
    @clients_list = @query_results
    render :partial => 'popup_sync_client', locals: {company_name: @client.company_name}
  end

  def sync_jurnal
    sleep 5
    render json: {results: t("clients.sync-jurnal-count", count: 4).html_safe}
  end

  def unsync_jurnal
    #todo nanti cm owner yg bisa ini
    redirect_to client_path(params[:client_id])
  end

  def init_repo_queries
    @industry_lists = [["Retail/Online Shop", 1], ["Jasa", 2], ["Konstruksi", 2]]
    @client_status_filter = [{id: 1, name: "All", count: 23}, 
                            {id: 2, name: "Jurnal", count: 11},
                            {id: 3, name: "Non Jurnal", count: 77},
                            {id: 4, name: "Need to Link", count: 12},
                            {id: 5, name: "Archived", count: nil}]

    @query_results = [
        Lead.new(1, SecureRandom.base64(8), ["email a", "email b"], "081222", "new lead", "Budi"), 
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(4, "hello there", ["email a", "email b"], "081333", "new lead", "Budi")]

    @client_status = [["Archived", "Archived"], ["Active", "Active"]]
  end

  def current_user
  end
end

app/views/clients/_client_details.html.haml
.col-xs-12.col-sm-3.filter-box.height-inherit-on-large
  .title-row.margin-bottom-15.padding-top-15
    = t("clients.index")
  .row
    .col-xs-12{onclick: "Turbolinks.visit('#{clients_path}');"}
      %span.glyphicon.glyphicon-menu-left.hover
      %span.title.margin-left-10.hover
        = client.company_name
  .row.margin-top-15
    .col-xs-2
      .custom-thumbnail
        = client.company_name.to_s.split(" ").map(&:first).join("").upcase
  .row.margin-top-15
    .col-xs-12.font-medium
      = client.contact_name
    .col-xs-12
      = client.phone
    .col-xs-12
      = client.email.join(", ")
    .col-xs-12
      Jasa Servis
    .col-xs-12
      = client.address
    .col-xs-12
      = client.description

  

app/views/clients/_lists.html.haml
- if choice == "4" #todo temporary for need-to-link choice
  %thead
    %tr
      %th.sort-header(data-sort="#{sort}" data-el="#search_sort")
        = t("form.jurnal-company-name").html_safe
      %th
  %tbody
    - @query_results.each do |r|
      %tr
        %td.align-middle
          = link_to "<div class='color-initial font-medium'>#{r.company_name}</div>".html_safe, client_path(r.id), class: 'hover'
        %td.text-right
          = form_for(r, url: render_sync_modal_client_path(r.id), method: :post, remote: :true, html: {class: "form-render-sync-modal", "data-ajax-target": "#target-render-sync-client-modal"}) do
            = hidden_field_tag :authenticity_token, form_authenticity_token
            = hidden_field_tag :id, r.id
            = button_tag t("clients.link-to-client"), class: "btn btn-light-blue"
- else
  %thead
    %tr
      %th.sort-header(data-sort="#{sort}" data-el="#search_sort")
        = t("form.company-name-full", required: "").html_safe
      %th.text-right
        = t("clients.to-do").html_safe
      %th
  %tbody
    - @query_results.each do |r|
      %tr
        %td
          = link_to "<div class='color-initial font-medium'>#{r.company_name}</div> <div class='font-12 grey'>#{r.email.join(", ")}</div>".html_safe, client_path(r.id), class: 'hover'
        %td.text-right.align-middle
          = link_to t("clients.to-do-total", total: r.id), client_path(r.id)
        %td.text-right
          //todo input validation if client have jurnal company
          %button.btn.btn-light-blue
            = t("clients.go-to-jurnal")

app/views/clients/_popup_new_client.html.haml
#popup-new-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("clients.create")
      .modal-body
        = form_tag(clients_path, method: :post, remote: :true, class: "custom-form", id: "form-create-client", "data-success-msg": t("clients.create-ok"), "data-error-msg": t("clients.create-error"), "data-ajax-target": "#target-form-result") do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("form.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true
              .form-group
                = label_tag :contact_name, t("form.contact-name")
                = text_field_tag :contact, nil, class: "form-control"
              .form-group
                = label_tag :phone_number, t("form.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("form.phone-format")
              .form-group
                = label_tag :email_address, t("form.email")
                = select_tag :email, [], class: "form-control select2-tags", multiple: true, "data-minimum-results-for-search": "Infinity"
              .form-group.use-caret
                = label_tag :industry, t("form.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("form.address")
                = text_field_tag :address, nil, class: "form-control"
              .form-group
                = label_tag :descriptions, t("form.desc")
                = text_area_tag :descriptions, nil, class: "form-control"
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.create"), form: "form-create-client", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/clients/_popup_sync_client.html.haml
#popup-sync-client.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("clients.link-to-client")
      .modal-body
        //todo sync ke company ini tar dpikirin url ny yg mana
        = form_for(@client, url: client_path(params[:id]), method: :patch, remote: :true, html: {class: "custom-form", id: "form-sync-client", "data-ajax-target": "#target-form-result"}) do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row.flex.align-items-center.flex-column
            .col-xs-12.text-center
              .form-group
                = t("clients.will-be-linked", company: company_name).html_safe
            .col-xs-6
              .form-group.use-caret
                = select_tag :client_id, options_from_collection_for_select(@clients_list, :id, :contact_name), class: "form-control select2-option", required: true, "data-placeholder": t("form.select-client-placeholder"), include_blank: true
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.save"), form: "form-sync-client", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/clients/_popup_sync_jurnal.html.haml
#popup-sync-jurnal.modal.fade.custom-modal(data-method="GET" data-action="#{sync_jurnal_clients_path}")
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("clients.sync-jurnal")
      .modal-body-loading
        .modal-body.text-center
          = t("clients.sync-jurnal-wait")
          %br
          %br
          %span.glyphicon.glyphicon-refresh.glyphicon-refresh-animate.font-50
        .modal-footer
          %button.btn.btn-grey.min-width-100(data-dismiss="modal")
            = t("btn.close")
      .modal-body-success.hidden
        .modal-body.text-center
          .message-success
          %br
          %br
          %span.glyphicon.glyphicon-refresh.font-50
        .modal-footer
          %button.btn.btn-green.min-width-100#see-list-btn(data-dismiss="modal" data-filter-value=filter_value)
            = t("clients.see-list-btn")

app/views/clients/_popup_update_client.html.haml
#popup-update-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("clients.update")
      .modal-body
        = form_for(@client, url: client_path(params[:id]), method: :patch, remote: :true, html: {class: "custom-form", id: "form-update-client", "data-success-msg": t("clients.update-ok"), "data-error-msg": t("clients.update-error")}) do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("form.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true, value: @client.company_name
              .form-group
                = label_tag :contact_name, t("form.contact-name")
                = text_field_tag :contact, nil, class: "form-control", value: @client.contact_name
              .form-group
                = label_tag :phone_number, t("form.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("form.phone-format"), value: @client.phone
              .form-group
                = label_tag :email_address, t("form.email")
                = select_tag :email, options_for_select(@client.email, @client.email), class: "form-control select2-tags", multiple: true
              .form-group.use-caret
                = label_tag :industry, t("form.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists, @industry_lists[2]), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("form.address")
                = text_field_tag :address, nil, class: "form-control", value: @client.address
              .form-group
                = label_tag :descriptions, t("form.desc")
                = text_area_tag :descriptions, nil, class: "form-control", value: @client.description
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.update"), form: "form-update-client", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/clients/index.html.haml
.container.overflow-scroll
  .row.height-inherit-on-large
    = render partial: "helpers/filter_box", locals: {choices: @client_status_filter, search_url: search_clients_path, title: t("clients.index"), search_placeholder: t("form.search-placeholder")}
    .col-xs-12.col-sm-9.padding-top-15
      .text-right.margin-bottom-15
        %span#sync-jurnal-wrapper.tool-tip(data-toggle="tooltip" data-placement="bottom" title="#{t("clients.sync-jurnal-btn-tooltip")}")
          %button.btn.btn-blue#popup-sync-jurnal-btn
            %span.glyphicon.glyphicon-refresh.margin-right-5
            = t("clients.sync-jurnal")
        %button.btn.btn-blue(data-toggle="modal" data-target="#popup-new-lead")
          = t("clients.new-btn")
      %table.table#target-form-result
        %thead
          %tr
            %th.sort-header(data-sort="desc" data-el="#search_sort")
              = t("form.company-name-full", required: "").html_safe
            %th.text-right
              = t("clients.to-do").html_safe
            %th
        %tbody
          %tr
            %td.color-inherit
              = link_to "<div class='color-initial font-medium'>companyName</div> <div class='font-12 grey'>email@emai.com</div>".html_safe, client_path(1), class: 'hover'
            %td.text-right.align-middle
              = link_to t("clients.to-do-total", total: 2), client_path(1)
            %td.text-right
              %button.btn.btn-light-blue
                = t("clients.go-to-jurnal")
      = render partial: "helpers/pagination", locals: {first_page: 1, last_page: @last_page, total_data: @total_data, current_data: @current_data}

#target-render-sync-client-modal

= render partial: "popup_new_client";
= render partial: "popup_sync_jurnal", locals: {filter_value: @filter_value};

app/views/clients/show.html.haml
.container.overflow-scroll#scrolling
  .row.height-inherit-on-large
    = render partial: "client_details", locals: {client: @client}
    .col-xs-12.col-sm-9.padding-top-15
      .row.visible-xs.margin-top-20.margin-bottom-20.border-top-bottom-lighter-grey
      .row-header
        .row
          .col-xs-6.font-16.flex.align-items-center
            .dropdown.flex.margin-left-10
              .box-grey.padding-0-10
                = @client.status
              %button.margin-left-5.glyphicon.glyphicon-triangle-bottom.padding-0-3.dropdown-toggle.box-grey#change-lead-status(data-toggle="dropdown")
              %ul.dropdown-menu.dropdown-menu-right
                - @client_status.each do |x|
                  %li
                    = link_to x[1], client_path(params[:id], status_id: x[0]), remote: :true, method: :patch, class: "dropdown-item toggle-change-lead-status"
          .col-xs-6.text-right
            .dropdown.custom.pull-right
              #dropdown-action.dropdown-toggle(data-toggle="dropdown")
                %span.glyphicon.glyphicon-option-horizontal
              %ul.dropdown-menu.dropdown-menu-right
                %li.dropdown-item
                  %a(data-toggle="modal" data-target="#popup-update-lead")
                    = t("btn.update")
                %li.dropdown-item
                  = link_to t("btn.delete"), client_path(params[:id]) ,"data-confirm": t("clients.prompt-delete"), method: :delete, "data-title": "#{t("form.delete-confirmation")}", "data-confirm-btn": "#{t("btn.delete")}", "data-confirm-btn-class": "btn-red btn min-width-100"
      .row.margin-top-20
        .col-xs-12.title.padding-bottom-10
          = t("clients.companies")
          %a.pull-right.custom-plus-icon(target="_blank" href="https://my.jurnal.id")
            +
        .col-xs-12
          %table.table
            %tbody
              - @clients_company.each do |c|
                %tr
                  %td.text-left
                    = c.company_name
                  %td.text-right
                    %button.btn.btn-light-blue.margin-right-10
                      = t("clients.go-to-jurnal")
                    .dropdown.pull-right.margin-top-5
                      #dropdown-action.dropdown-toggle(data-toggle="dropdown")
                        %span.glyphicon.glyphicon-option-vertical.font-20.grey
                      %ul.dropdown-menu.dropdown-menu-right
                        %li.dropdown-item
                          = link_to t("clients.unlink-company"), unsync_jurnal_client_path(c.id, client_id: params[:id]) ,"data-confirm": t("clients.prompt-unlink"), method: :post, "data-title": "#{t("clients.unlink-company")}", "data-confirm-btn": "#{t("btn.confirm")}", class: "dropdown-menu-link grey", "data-confirm-btn-class": "btn-red btn min-width-100"
      .row.margin-top-50
        .col-xs-12.title.padding-bottom-10
          = t("activity.title")
          .pull-right.custom-plus-icon(data-toggle="modal" data-target="#popup-new-activity")
            +
        .col-xs-12
          %table.table
            %tbody.scroll-container
              = render partial: "activities/lists", locals: {lists: @query_results}
          .scroll-element.overflow-scroll(data-pagination-endpoint=activity_path data-pagination-pages="#{@total_pages}" data-current-page=1 colspan=3)
          .text-center.scroll-loading
            %span.glyphicon.glyphicon-repeat.glyphicon-refresh-animate

= render partial: "popup_update_client";
= render partial: "activities/popup_new_activity";
= render partial: "helpers/popup_confirm";

- content_for :scripts do
  = javascript_include_tag "activity-list", "data-turbolinks-track" => true