config/routes.rb
Rails.application.routes.draw do
  root "leads#index"

  devise_for :members, path: '', controllers: {
    confirmations: 'members/confirmations',
    passwords: 'members/passwords',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    unlocks: 'members/unlocks'
  }

  devise_for :admins, path: 'admin', controllers: {
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks'
  }

  namespace :admins do
    get "/", to: "admins#index"
    resources :partners
    resources :leads
  end
  
  resources :leads do
    collection do
      post :search
    end
    member do
      post :convert_client
    end
  end

  resources :clients do
    collection do
      post :search
      get :sync_jurnal
    end
    member do
      post :render_sync_modal
      post :unsync_jurnal
    end
  end

  resources :teams do
    collection do
      post :search
    end
    member do
      patch :reactive
    end
  end
  
  resources :activities do
    member do
      post :render_update_modal
    end
  end

  get 'health', to: 'health#show'
end

app/models/lead.rb
# ini sementara pake virtus model dulu, karena pake form for di front end nya
class Lead
  include ActiveModel::Model
  include Virtus::Model

  attribute :company_name, String
  attribute :contact_name, String
  attribute :phone, String
  attribute :email, String
  attribute :status, String
  attribute :industry, String
  attribute :address, String
  attribute :description, String
  attribute :member_id, Integer
  attribute :id, Integer
end

app/controllers/admins/leads_controller.rb
class Admins::LeadsController < Admins::AdminsController
  def index
    
  end
end

app/controllers/leads_controller.rb
require "#{Rails.root}/lib/domain/leads/leads"

class LeadsController < ApplicationController
  before_action :authenticate_member!
  before_action :init_repo_queries

  def index
    @last_page = 10
    @current_data = 1 #@query_results.count
    @total_data = 25
  end

  def create
    render :partial => 'lists', locals: {sort: "desc"}
  end

  def show
    @total_pages = 4
    lead_repository
    @lead = @repo.load(id: params[:id])
  end

  def update
    params[:id] # lead = Lead.find(params[:id])
    params[:status_id] # update lead status with this
    redirect_to lead_path(params[:id])
  end

  def destroy
    redirect_to leads_path
  end

  def convert_client
    #create new client, get id
    new_client_id = params[:id]
    redirect_to client_path(new_client_id)
  end

  def search
    if params[:search_sort] == "desc"
      @query_results = @query_results.sort_by{|x| x.company_name.downcase}.reverse!
    else
      @query_results = @query_results.sort_by{|x| x.company_name.downcase}
    end

    render :partial => 'lists', locals: {sort: params[:search_sort]}
  end

  # remove later
  def init_repo_queries
    @industry_lists = [["Retail/Online Shop", 1], ["Jasa", 2], ["Konstruksi", 2]]
    @leads_status_filter = [{id: 1, name: "All", count: 23},
                      {id: 2, name: "New Leads", count: 4},
                      {id: 3, name: "In Progress", count: 5},
                      [{name: "Closed"},
                        [{id: 5, name: "Won", count: 6},
                          {id: 6, name: "Lost", count: 1},
                          {id: 7, name: "Junk", count: 2},
                          {id: 8, name: "Unreachable", count: 0},
                          {id: 9, name: "Underqualified", count: 11},
                          {id: 10, name: "Void/Duplicate", count: 2},
                          {id: 11, name: "Product/Feature", count: 3}]]]

    @leads_status = [["new lead", "new lead"], ["closed", "closed"], ["in progress", "in progress"], ["won", "won"]]
  end

  def lead_repository
    @repo = LeadRepository.new
  end
end

app/views/leads/_lists.html.haml
%thead
  %tr
    %th.sort-header(data-sort="#{sort}" data-el="#search_sort")
      = t("form.company-name-full", required: "").html_safe
    %th
      = t("form.email-full").html_safe
    %th
      = t("form.contact-full").html_safe
    %th
      = t("form.status")
%tbody
  - @query_results.each do |r|
    %tr
      %td
        = link_to r.company_name, lead_path(r.id), class: 'color-initial'
      %td
        = r.email.join(", ")
      %td
        = r.phone
      %td
        = r.status

app/views/leads/_popup_new_lead.html.haml
#popup-new-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("leads.create")
      .modal-body
        = form_tag(leads_path, method: :post, remote: :true, class: "custom-form", id: "form-create-lead", "data-success-msg": t("leads.create-ok"), "data-error-msg": t("leads.create-error"), "data-ajax-target": "#target-form-result") do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("form.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true
              .form-group
                = label_tag :contact_name, t("form.contact-name")
                = text_field_tag :contact, nil, class: "form-control"
              .form-group
                = label_tag :phone_number, t("form.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("form.phone-format")
              .form-group
                = label_tag :email_address, t("form.email")
                = select_tag :email, [], class: "form-control select2-tags", multiple: true
              .form-group.use-caret
                = label_tag :industry, t("form.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("form.address")
                = text_field_tag :address, nil, class: "form-control"
              .form-group
                = label_tag :descriptions, t("form.desc")
                = text_area_tag :descriptions, nil, class: "form-control"
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.create"), form: "form-create-lead", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/leads/_popup_update_lead.html.haml
#popup-update-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("leads.update")
      .modal-body
        = form_for(@lead, url: lead_path(params[:id]), method: :patch, remote: :true, html: {class: "custom-form", id: "form-update-lead", "data-success-msg": t("leads.update-ok"), "data-error-msg": t("leads.update-error")}) do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("form.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true, value: @lead.company_name
              .form-group
                = label_tag :contact_name, t("form.contact-name")
                = text_field_tag :contact, nil, class: "form-control", value: @lead.contact_name
              .form-group
                = label_tag :phone_number, t("form.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("form.phone-format"), value: @lead.phone
              .form-group
                = label_tag :email_address, t("form.email")
                = select_tag :email, options_for_select(@lead.email, @lead.email), class: "form-control select2-tags", multiple: true
              .form-group.use-caret
                = label_tag :industry, t("form.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists, @industry_lists[2]), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("form.address")
                = text_field_tag :address, nil, class: "form-control", value: @lead.address
              .form-group
                = label_tag :descriptions, t("form.desc")
                = text_area_tag :descriptions, nil, class: "form-control", value: @lead.description
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.update"), form: "form-update-lead", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/leads/index.html.haml
.container.overflow-scroll
  .row.height-inherit-on-large
    = render partial: "helpers/filter_box", locals: {choices: @leads_status_filter, search_url: search_leads_path, title: t("leads.index"), search_placeholder: t("form.search-placeholder")}
    .col-xs-12.col-sm-9.padding-top-15
      .text-right.margin-bottom-15
        %button.btn.btn-blue(data-toggle="modal" data-target="#popup-new-lead")
          = t("leads.new-btn")
      %table.table#target-form-result
        %thead
          %tr
            %th.sort-header(data-sort="desc" data-el="#search_sort")
              = t("form.company-name-full", required: "").html_safe
            %th
              = t("form.email-full").html_safe
            %th
              = t("form.contact-full").html_safe
            %th
              = t("form.status")
        %tbody
          %tr
            %td
              = link_to "Shadow Shadow", lead_path(1), class: 'color-initial'
            %td
              hello
            %td
              hello
            %td
              hello
      = render partial: "helpers/pagination", locals: {first_page: 1, last_page: @last_page, total_data: @total_data, current_data: @current_data}

= render partial: "popup_new_lead";

app/views/leads/show.html.haml
.container.overflow-scroll#scrolling
  .row.height-inherit-on-large
    = render partial: "helpers/filter_box", locals: {choices: @leads_status_filter, search_url: search_leads_path, title: t("leads.index"), search_placeholder: t("form.search-placeholder")}
    .col-xs-12.col-sm-9.padding-top-15
      .row-header
        .row
          .col-xs-6.font-16.flex.align-items-center
            %span.glyphicon.glyphicon-menu-left.hover{onclick: "Turbolinks.visit('#{leads_path}');"}
            .title.margin-left-10.hover{onclick: "Turbolinks.visit('#{leads_path}');"}
              = @lead.company_name
            .dropdown.flex.margin-left-10
              .box-grey.padding-0-10
                = @lead.status
              %button.margin-left-5.glyphicon.glyphicon-triangle-bottom.padding-0-3.dropdown-toggle.box-grey#change-lead-status(data-toggle="dropdown")
              %ul.dropdown-menu.dropdown-menu-right
                - @leads_status.each do |x|
                  %li
                    = link_to x[1], lead_path(params[:id], leads_status_id: x[0]), remote: :true, method: :patch, class: "dropdown-item toggle-change-lead-status"
          .col-xs-6.text-right
            = link_to t("leads.convert-client"), convert_client_lead_path(id: @lead.id) ,"data-confirm": t("leads.prompt-convert-client"), method: :post, "data-title": "#{t("leads.convert-client")}", "data-confirm-btn": "#{t("btn.confirm")}", class: "btn btn-green", "data-confirm-btn-class": "btn-green btn min-width-100"
            .dropdown.custom.pull-right
              #dropdown-action.dropdown-toggle(data-toggle="dropdown")
                %span.glyphicon.glyphicon-option-horizontal
              %ul.dropdown-menu.dropdown-menu-right
                %li.dropdown-item
                  %a(data-toggle="modal" data-target="#popup-update-lead")
                    = t("btn.update")
                %li.dropdown-item
                  = link_to t("btn.delete"), lead_path(params[:id]) ,"data-confirm": t("leads.prompt-delete"), method: :delete, "data-title": "#{t("form.delete-confirmation")}", "data-confirm-btn": "#{t("btn.delete")}", "data-confirm-btn-class": "btn-red btn min-width-100"
        .row
          .col-xs-2
            .custom-thumbnail
              = @lead.company_name.to_s.split(" ").map(&:first).join("").upcase
          .col-xs-12.col-sm-2
            %div
              = @lead.contact_name
            %div
              = @lead.phone
            %div
              = @lead.email
            %div
              = @lead.industry
            %div
              = @lead.address
            %div
              = @lead.description
      .row.margin-top-50
        .col-xs-12.title.padding-bottom-10
          = t("activity.title")
          .pull-right.custom-plus-icon(data-toggle="modal" data-target="#popup-new-activity")
            +
        .col-xs-12
          %table.table
            %tbody.scroll-container
              / = render partial: "activities/lists", locals: {lists: @query_results}
          .scroll-element.overflow-scroll(data-pagination-endpoint=activity_path data-pagination-pages="#{@total_pages}" data-current-page=1 colspan=3)
          .text-center.scroll-loading
            %span.glyphicon.glyphicon-repeat.glyphicon-refresh-animate

= render partial: "popup_update_lead";
= render partial: "activities/popup_new_activity"
= render partial: "helpers/popup_confirm"

- content_for :scripts do
  = javascript_include_tag "activity-list", "data-turbolinks-track" => true