config/routes.rb
Rails.application.routes.draw do
  root "leads#index"

  devise_for :members, path: '', controllers: {
    confirmations: 'members/confirmations',
    passwords: 'members/passwords',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    unlocks: 'members/unlocks'
  }

  devise_for :admins, path: 'admin', controllers: {
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks'
  }

  namespace :admins do
    get "/", to: "admins#index"
    resources :partners
    resources :leads
  end
  
  resources :leads do
    collection do
      post :search
    end
    member do
      post :convert_client
    end
  end

  resources :clients do
    collection do
      post :search
      get :sync_jurnal
    end
    member do
      post :render_sync_modal
      post :unsync_jurnal
    end
  end

  resources :teams do
    collection do
      post :search
    end
    member do
      patch :reactive
    end
  end
  
  resources :activities do
    member do
      post :render_update_modal
    end
  end

  get 'health', to: 'health#show'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  def initialize(params={})
    super

    @created_at = DateTime.now
    @updated_at = DateTime.now
    @version = 0
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_member!

  def show
    @total_pages = 4
    @current_pages = 1
    activity_repo
    @lists = @repo.load_collection(params[:id])
    render partial: 'activities/lists'
  end

  def new
  end

  def create
    params[:status] || "false" #checkbox ngirimny bentuk string
    params[:due_date] || nil
    params[:description] || nil
    if params[:status].present? #temporary, later change to if model.save
      redirect_to lead_path(params[:lead_id])
    else
      redirect_to lead_path(params[:lead_id])
    end
  end

  def update
    render json: {id: 1, status: "true", due_date: Time.now, description: "Random Cat"}
  end

  def destroy
    redirect_to lead_path(params[:lead_id])
  end

  def render_update_modal
    @activity = Activity.find(4)
    render :partial => 'popup_update_activity'
  end

  def activity_repo
    @repo = ActivityRepository.new
  end
end

app/views/activities/_lists.html.haml
- @lists.each do |i|
  %tr(data-activity-id="#{i[:id]}")
    %td{style: "width:25%;"}
      = i[:activity_due_date].try(:strftime, "%d/%m/%Y" )
    %td.activity-desc
      = i[:activity_description]
    %td
      .text-right.font-12.flex.justify-content-flex-end
        .margin-right-10
          .status-color.grey
          .grey
            = i[:member_name]
        .dropdown.pull-right
          #dropdown-action.dropdown-toggle(data-toggle="dropdown")
            %span.glyphicon.glyphicon-option-vertical.font-20.grey
          %ul.dropdown-menu.dropdown-menu-right
            %li.dropdown-item
              = form_for(i, url: render_update_modal_activity_path(i[:id]), method: :post, remote: :true, html: {class: "form-render-update-activity-modal", "data-ajax-target": "#target-render-update-activity-modal"}) do
                = hidden_field_tag :authenticity_token, form_authenticity_token
                = button_tag t("btn.update"), class: "dropdown-menu-link"
            %li.dropdown-item
              = link_to t("btn.delete"), activity_path(i[:id], lead_id: params[:id]) ,"data-confirm": t("activity.prompt-delete"), method: :delete, "data-title": "#{t("form.delete-confirmation")}", "data-confirm-btn": "#{t("btn.delete")}", class: "dropdown-menu-link", "data-confirm-btn-class": "btn-red btn min-width-100"

#target-render-update-activity-modal

app/views/activities/_popup_new_activity.html.haml
#popup-new-activity.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("activity.create")
      .modal-body
        = form_tag(activities_path, method: :post, remote: :true, class: "custom-form", id: "form-create-activity", "data-ajax-target": "#target-form-result") do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          = hidden_field_tag :lead_id, params[:id]
          .row
            .col-xs-6
              = label_tag :status
              .padding-left-5
                %label.switch
                  = check_box_tag :status, true, false, id: 'input-toggle'
                  %span.slider.round
                  %span.closed
                    Closed
                  %span.active
                    Open
            .col-xs-6#target-toggle
              = label_tag :due_date
              .form-group.has-feedback.left
                = text_field_tag :due_date, nil, class: "form-control", "data-provide": "datepicker", "data-date-autoclose": true, disabled: true
                %span.glyphicon.glyphicon-calendar.form-control-feedback.left
          .row.margin-top-10
            .col-xs-12
              = label_tag :description
              = text_area_tag :description, nil, class: "form-control"
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.create"), form: "form-create-activity", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}

app/views/activities/_popup_update_activity.html.haml
#popup-update-activity.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("activity.update")
      .modal-body
        - if @activity.present?
          = form_for(@activity, url: activity_path, method: :patch, remote: :true, html: {class: "custom-form", id: "form-update-activity"}) do
            = hidden_field_tag :authenticity_token, form_authenticity_token
            = hidden_field_tag :lead_id, params[:id]
            .row
              .col-xs-6
                = label_tag :status
                .padding-left-5
                  %label.switch
                    = check_box_tag :status, true, @activity.status, id: 'input-toggle'
                    %span.slider.round
                    %span.closed
                      Closed
                    %span.active
                      Open
              .col-xs-6#target-toggle
                = label_tag :due_date
                .form-group.has-feedback.left
                  = text_field_tag :due_date, nil, class: "form-control", "data-provide": "datepicker", "data-date-autoclose": true, disabled: true, value: @activity.due_date.try(:strftime, "%m/%d/%Y")
                  %span.glyphicon.glyphicon-calendar.form-control-feedback.left
            .row.margin-top-10
              .col-xs-12
                = label_tag :description
                = text_area_tag :description, nil, class: "form-control", value: @activity.description
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = button_tag t("btn.update"), form: "form-update-activity", class: "btn btn-green min-width-100", data: {disable_with: t("btn.process").html_safe}