config/routes.rb
Rails.application.routes.draw do
  root "leads#index"

  devise_for :members, path: '', controllers: {
    confirmations: 'members/confirmations',
    passwords: 'members/passwords',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    unlocks: 'members/unlocks'
  }

  devise_for :admins, path: 'admin', controllers: {
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks'
  }

  namespace :admins do
    get "/", to: "admins#index"
    resources :partners
    resources :leads
  end
  
  resources :leads do
    collection do
      post :search
    end
    member do
      post :convert_client
    end
  end

  resources :clients do
    collection do
      post :search
      get :sync_jurnal
    end
    member do
      post :render_sync_modal
      post :unsync_jurnal
    end
  end

  resources :teams do
    collection do
      post :search
    end
    member do
      patch :reactive
    end
  end
  
  resources :activities do
    member do
      post :render_update_modal
    end
  end

  get 'health', to: 'health#show'
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CrmPartner
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('icons/jurnal-icon.png')
    = stylesheet_link_tag    'application_admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application_admin', 'data-turbolinks-track': 'reload'
    = yield :scripts
    - if notice.present?
      .alert.alert-info.fade.in
        %a.close(data-dismiss="alert" aria-label="Close")
          &times;
        = notice
    - if alert.present?
      .alert.alert-danger.fade.in
        %a.close(data-dismiss="alert" aria-label="Close")
          &times;
        = alert
%body
  %nav
    %li
      .title.font-18.font-regular
        = t("admin.index-partner")
    %li
      = link_to t("partner.index"), admins_partners_path, class: "#{current_page?(admins_partners_path) ?  'active' : '' }"
    %li
      = link_to t("leads.index"), admins_leads_path, class: "#{current_page?(admins_leads_path) ?  'active' : '' }"
    %li
      = link_to t("admin.index"), admins_path, class: "#{current_page?(admins_path) ?  'active' : '' }"
    %li
      %span.dropdown.pull-right
        %span.dropdown-toggle(data-toggle="dropdown")
          .glyphicon.glyphicon-user.font-12.margin-right-5
          = current_admin.try(:name)
          .glyphicon.glyphicon-triangle-bottom.font-12.margin-left-5
        %ul.dropdown-menu.dropdown-menu-right
          %li.dropdown-item
            = link_to t("menu.logout"), destroy_admin_session_path, method: :delete, class: 'grey'
  = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CrmPartner
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('icons/jurnal-icon.png')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :scripts
  %body
    %nav
      %ul
        %li.nav-border
          = image_tag "icons/jurnal-icon.png"
        %li
          = link_to (image_tag "https://s3-ap-southeast-1.amazonaws.com/jurnal-quickbook-s3/images/icon_apps.svg"), leads_path, title: t("leads.tooltip"), "data-toggle": "tooltip", "data-placement": "right"
        %li
          = link_to (image_tag "https://s3-ap-southeast-1.amazonaws.com/jurnal-quickbook-s3/images/icon_apps.svg"), clients_path, title: t("clients.tooltip"), "data-toggle": "tooltip", "data-placement": "right"
        .nav-bottom
          %li
            = link_to (image_tag "https://s3-ap-southeast-1.amazonaws.com/jurnal-quickbook-s3/images/icon_apps.svg"), teams_path, title: t("teams.tooltip"), "data-toggle": "tooltip", "data-placement": "right"
          %li
            .dropdown
              %a.dropdown-toggle(data-toggle="dropdown")
                = image_tag "https://s3-ap-southeast-1.amazonaws.com/jurnal-quickbook-s3/images/icon_apps.svg"
              %ul.dropdown-menu.dropdown-menu-right.custom
                %li.dropdown-item
                  %div
                    %span.status-profile
                    = current_member.name
                %li.dropdown-item
                  //todo if owner clickable, else just text
                  = link_to "PT. Jurnal", '#'
                %li.dropdown-item
                  = link_to t("menu.logout"), destroy_member_session_path, method: :delete
    = yield

app/views/layouts/blank.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CrmPartner
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('icons/jurnal-icon.png')
    = stylesheet_link_tag    'application_blank', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application_blank', 'data-turbolinks-track': 'reload'
    = yield :scripts
    - if notice.present?
      .alert.alert-info.fade.in
        %a.close(data-dismiss="alert" aria-label="Close")
          &times;
        = notice
    - if alert.present?
      .alert.alert-danger.fade.in
        %a.close(data-dismiss="alert" aria-label="Close")
          &times;
        = alert
%body
  = yield